apiVersion: v1
kind: Secret
metadata:
  name: dentalclinic-secrets
  namespace: k8s-duha
type: Opaque
data:
  DB_PASSWORD: cm9vdA==   # "root" base64 encoded
  JWT_SECRET: dGVzdHNlY3JldA==  # "testsecret" base64 encoded